services:
  chat-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - chat_data:/var/lib/postgresql/data

  chat-service:
      build:
        context: ./chat-service
      command: python manage.py runserver 0.0.0.0:8001
      volumes:
        - ./chat-service:/app
        - chat_media:/app/media
      ports:
        - "8001:8001"
      depends_on:
        - chat-db
      env_file:
        - .env
  users-db:
    image: postgres:15-alpine #lekki, a latest sie moze wykrzaczyć
    container_name: users_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data

  users-service:
    build: ./users-service
    container_name: users_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./users-service:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - users-db

volumes:
  postgres_users_data:
  chat_data:
  chat_media: